wheel_model:
  description: 'Wheel model'
  choices: ['moog']
  default_value: 'moog'
laser_model:
  description: 'Base laser model'
  choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
  default_value: 'sick-571'
add_on_module:
  description: 'Whether the base has an add-on module'
  choices: ['no-add-on', 'cobra']
  default_value: 'no-add-on'
camera_model:
  description: 'Camera model'
  choices: ['no-camera', 'realsense-d435', 'realsense-d435i']
  default_value: 'no-camera'
